name: Handle Github Issues
on:
  issues:
    types:
      - opened
      - reopened
      - closed
jobs:
  handle-issues:
    uses: "./.github/workflows/reusable-handle-issues-workflow.yaml"
    permissions:
      issues: write
      contents: read
      projects: write
    with:
      incoming_column: Incoming
      done_column: Done
      project_id: 5
    secrets:
      gh_app_secret_key: ${{ secrets.PROJECTS_UPDATE_APP_PEM }}
